global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "cashflow-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8000"]
    scrape_interval: 5s

  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
    metrics_path: /metrics

  - job_name: "flower"
    static_configs:
      - targets: ["flower:5555"]
    metrics_path: /metrics

  # Node exporter for system metrics
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
